configuration: Release

init:
  - cmd: set
  
install: 
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
     
before_build:
  - cmd: nuget restore Refit.sln
  - cmd: '.\packages\GitVersion.CommandLine\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo'
  
build:
  verbosity: normal
  parallel: true
  project: Refit.sln
  
after_build:
  - cmd: nuget pack Refit\Refit.nuspec -version "%GitVersion_NuGetVersionV2%" -prop "target=%CONFIGURATION%" -NoPackageAnalysis
  - cmd: appveyor PushArtifact "Refit.%GitVersion_NuGetVersion%.nupkg"  
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/refit/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
